const mot = {
    "facile":["ABDOS","BELIER","CAJUN","DEFIT","FREIN","GUERI","HARPE","JAPON","KOALA","MOYEN"],
    "moyen":["BAPTISER","ZENITUDE","VIOLENTS","TUNIQUES","TRAMWAYS","SYNTAXES","SURDOSER","QUIETUDE","PLONGEUR","OBJECTIF"],
    "difficile":["ACCOMPAGNER","ALGORITHMES","CAPILLARITE","CHROMATIQUE","EXPORTATION","FEUILLETAGE","FOLKLORIQUE","GASTRONOMES","VULNERABLES","TUYAUTERIES"]
};